# Generated by Django 5.2.4 on 2025-08-13 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='instagram/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetailRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chef', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('prep_time', models.IntegerField(default=0)),
                ('cook_time', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='details/')),
                ('description', models.TextField()),
                ('calories', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('protein', models.FloatField(default=0)),
                ('carbohydrate', models.FloatField(default=0)),
                ('cholesterol', models.FloatField(default=0)),
                ('ingredient', models.CharField(choices=[('For main dishes', 'For main dishes'), ('For the sauce', 'For the sauce')], max_length=100)),
                ('direction_title', models.CharField(max_length=100)),
                ('direction_img', models.ImageField(blank=True, null=True, upload_to='directions/')),
                ('direction_text', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HotRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='hot-recipes/')),
                ('prep_time', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('chef', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='recipes/')),
                ('prep_time', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
