# Generated by Django 5.2.4 on 2025-08-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotrecipe',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
