# Generated by Django 5.2.4 on 2025-08-14 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hotrecipe_description_recipe_is_starred'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='blogs/')),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('author_img', models.ImageField(upload_to='blogs/authors/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('author_img', models.ImageField(upload_to='blog-post/authors/')),
                ('img', models.ImageField(upload_to='blog-post/')),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='main.blogpost')),
            ],
        ),
    ]
