# Generated by Django 5.2.4 on 2025-08-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_bloglist_blogpost_blogfaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='TastyRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='tasty-recipes/')),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bloglist',
            options={'ordering': ['-date'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
