# Generated by Django 5.2.4 on 2025-08-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tastyrecipe_alter_bloglist_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogfaq',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog-post/faqs/'),
        ),
    ]
